### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by snicoll**

### CODE REVIEW

**Comment by hzpz** [comment]
Already done, but thanks anyway. New artifact has been pushed and awaits sync to Central.

**Comment by snicoll** [comment]
I just push 3 minutes before you ;) Anyway, looks good to me. I'll add it to the 3rd party starters, thanks!

**Comment by hzpz** [comment]
I didn't see it, sorry. But you didn't change the version anyway ;-) Thanks again!

**Comment by snicoll** [comment]
:smile:

**Pull request closed without merging**
